Tweets/index
yasufinc/kenshu3 pull request #6
Opened 2021-09-25 11:15 UTC by yasufinc

## 背景
フォローしている人タイムラインページの作成

## やったこと
tweets/indexに対応するビューとコントローラーの作成

## あえてやらなかったこと
特になし

2021-09-26 07:23 UTC, RyuseiIkezawa commented
@yasufinc #5 をmainにmergeしたら、mainをこのブランチにmergeするか rebaseをお願いします

2021-09-26 07:38 UTC, RyuseiIkezawa requested changes
commented

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/controllers/tweets_controller.rb
> +    #@tweet = MyThread.create(tweet_params)
関係のないコードは消すようにしよう！

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/controllers/tweets_controller.rb
> +      render 'edit'
メッセージは出さない？

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/models/user.rb
> +  has_many :tweets
ユーザーが削除された場合、紐づくツイートがデータとして残ることになるけど、それで良しとする？（ユーザーが消えても、そのユーザーのツイートは消えない仕様？）

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/views/devise/registrations/new.html.erb
> +<h2>Sign up</h2>
そういえば、nameってどのタイミングで入力させるんだっけ？

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/views/layouts/application.html.erb
> +          <%= p "ログイン中のユーザ: #{current_user.email}さん" %>
nameを出してあげる方が良いのかな？

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/views/tweets/_form.html.erb
> +    <%= form.text_field :content %>
`textarea` とかの方が良さそうではある！
（修正は任せる！）

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/models/tweet.rb
> +class Tweet < ApplicationRecord
`publicity` は enumで扱えると良さそう！

2021-09-26 07:38 UTC, RyuseiIkezawa commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
これってUI上、どうやって表示される？ 1,2,3 ??

2021-09-26 07:38 UTC, RyuseiIkezawa commented on spec/requests/tweets_spec.rb
> +  describe "GET /index" do
どこかのタイミングでrspec書いていきたいな
requests だけでもいいので

タイミングを相談したいです

2021-09-27 02:34 UTC, yasufinc commented on app/models/user.rb
> +  has_many :tweets
関連データも同時に削除できるようにします！
dependent: :destroyを追加しました！

2021-09-27 02:36 UTC, yasufinc commented on app/views/layouts/application.html.erb
> +          <%= p "ログイン中のユーザ: #{current_user.email}さん" %>
了解です！

2021-09-27 02:39 UTC, yasufinc commented on app/views/tweets/_form.html.erb
> +    <%= form.text_field :content %>
了解です！

2021-09-27 02:40 UTC, yasufinc commented on app/views/devise/registrations/new.html.erb
> +<h2>Sign up</h2>
ユーザ作成時に入力させます！（ユーザ名・メアド・パスワード）
ログイン時は、メアドとパスワードのみで入れます！

2021-09-27 02:41 UTC, yasufinc commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
これいま1,2,3になってます

2021-09-27 04:53 UTC, yasufinc commented on spec/requests/tweets_spec.rb
> +  describe "GET /index" do
今日のMTGでお願いします！

2021-09-27 04:56 UTC, RyuseiIkezawa commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
どこかで修正予定のもの？
https://github.com/yasufinc/kenshu3/pull/6#discussion_r716158572
と合わせて修正しちゃった方が良いかなと思う！

「rails enum」「rails enum selectbox」 とかでググってもらえると！

2021-09-27 04:57 UTC, yasufinc commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
あ、現在はそれと合わせて修正できています。
全体公開・フォロワーのみに公開・非公開と表示されています。

2021-09-27 04:59 UTC, RyuseiIkezawa commented on app/controllers/tweets_controller.rb
> +      render 'edit', notice: 'Tweetの更新に失敗しました。'
render で noticeいけたっけ？
あとalertの方が適切なのかな

2021-09-27 05:02 UTC, yasufinc commented on app/controllers/tweets_controller.rb
> +      render 'edit'
ここのメッセージとは、なんのことでしょうか？
tweet.updateに失敗した際の、エラーメッセージということですか？

2021-09-27 05:02 UTC, RyuseiIkezawa commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
あ、修正されてた！

`Tweet. publicities.keys` とかで呼び出せた方が良いかなと思った！
publicityが変更された時に、viewも変更しなければいけなくなるので

2021-09-27 05:04 UTC, shunsakai commented on app/controllers/tweets_controller.rb
> +    @tweets = Tweet.all
all を使うのは現段階ではOKだが、のちに問題になると思われる。理由を考えられるとGood

2021-09-27 05:04 UTC, shunsakai commented on app/controllers/tweets_controller.rb
> +    @tweets = Tweet.all
表示順などは問題ないだろうか？

2021-09-27 05:04 UTC, shunsakai commented on app/controllers/tweets_controller.rb
> +    def user_check
check は命名としてイマイチなのと、関数(メソッド)名は 動詞で始まるように命名したい

2021-09-27 05:04 UTC, shunsakai commented on app/controllers/tweets_controller.rb
> +    user_check
```suggestion
    current_user.tweets.where(id: params[:id]).first
```
例えばこんな感じでもやりたいことは実現できそうかな

2021-09-27 05:04 UTC, shunsakai commented on app/models/tweet.rb
> +  enum publicity: {"全体公開":0, "フォロワーのみに公開":1, "非公開":2}
enum の場合は日本語で定義するより、コード (:public, :follower_only, :private) にしておくのが良さそう
「全体公開」という日本語での表示名は変わりうるが、publicity が public であることは変わらないので

2021-09-27 05:04 UTC, shunsakai commented on app/views/layouts/application.html.erb
> +      <% if user_signed_in? %>
これってdevise 組み込みのメソッドでしたっけ？
current_user の有無判定だけでも十分かと思いましたが

2021-09-27 05:04 UTC, shunsakai commented on app/views/tweets/edit.html.erb
> +<%= render 'form', tweet: @tweet%>
partial でのview 実装、Good

2021-09-27 05:44 UTC, yasufinc commented on app/controllers/tweets_controller.rb
> +    @tweets = Tweet.all
ゆくゆくDBの情報が増えて、ページネーションを導入する必要が出てきた時に、Tweet.allの使用は計算コストを増大させてしまうからでしょうか？？

2021-09-27 06:08 UTC, yasufinc commented on app/controllers/tweets_controller.rb
> +      render 'edit', notice: 'Tweetの更新に失敗しました。'
flash[:alert]にしました。

2021-09-27 06:09 UTC, yasufinc commented on app/views/tweets/_form.html.erb
> +    <%= form.select :publicity, [1,2,3] %>
了解です。変更しておきました。

2021-09-27 06:45 UTC, shunsakai commented on app/models/tweet.rb
> +  enum publicity: {Public: 0, Follower_only: 1, Private: 2}
```suggestion
  enum publicity: { public: 0, follower_only: 1, private: 2 }
```

2021-09-27 06:52 UTC, shunsakai approved these changes

2021-09-27 06:53 UTC, RyuseiIkezawa approved these changes

2021-09-27 06:53 UTC, merged